
name:         Bovine Hero Blog
description:  Bovine Hero's Blog 
url:          https://bovinehero.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  authors:
    output: true
  topics:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"