# Example Site settings

google_analytics: UA-141693864-1


author: bhero

title: Bovine Hero's Blog
email: tech_blog@bovinehero.com
description: >- # this means to ignore newlines until "twitter_username:"
  bovine hero's escapades in learning computer security.

twitter_username: BovineHero
github_username:  bovinehero

header_pages:
  - index.md
  - blog.md
  - documents.md
  
  

footer: 'follow us on <a href="https://twitter.com/bovinehero">twitter</a>'

#style: light # dark (default) or light
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-seo-tag
  - jekyll-paginate